CREATE TABLE [dbo].[lrContainer] (
    [lrContainerId]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [lrHeaderId]                  BIGINT        NULL,
    [lrName]                      VARCHAR (50)  NULL,
    [containerTypeId]             INT           NULL,
    [containerSeq]                INT           NOT NULL,
    [containerNo]                 VARCHAR (20)  NULL,
    [earlyShipDate]               DATE          NULL,
    [lateShipDate]                DATE          NULL,
    [portId]                      INT           NULL,
    [notes]                       VARCHAR (200) NULL,
    [cargoReadyDate]              SMALLDATETIME NULL,
    [forwarderId]                 INT           NULL,
    [forwarderBookingId]          VARCHAR (30)  NULL,
    [forwarderBookingDate]        DATE          NULL,
    [forwarderReplyDate]          DATE          NULL,
    [forwarderSICutOffDate]       DATE          NULL,
    [forwarderBookingNo]          VARCHAR (30)  NULL,
    [haulierId]                   INT           NULL,
    [ETD]                         DATE          NULL,
    [ETA]                         DATE          NULL,
    [MAAP]                        VARCHAR (30)  NULL,
    [Pouch]                       VARCHAR (30)  NULL,
    [containerSealNo]             VARCHAR (100) NULL,
    [containerMaxGross]           DECIMAL (14)  NULL,
    [containerTare]               DECIMAL (14)  NULL,
    [containerPullInDate]         SMALLDATETIME NULL,
    [containerPullOutDate]        SMALLDATETIME NULL,
    [containerStatus]             INT           NULL,
    [enterBy]                     INT           NOT NULL,
    [enterDate]                   DATETIME      CONSTRAINT [DF_lrContainer_enterDate] DEFAULT (getdate()) NOT NULL,
    [updateBy]                    INT           NULL,
    [updateDate]                  DATETIME      NULL,
    [lrCancelBy]                  INT           NULL,
    [lrCancelDate]                DATETIME      NULL,
    [containerConfirmDate]        DATETIME      NULL,
    [containerConfirmBy]          INT           NULL,
    [containerApproveDate]        DATETIME      NULL,
    [containerApproveBy]          INT           NULL,
    [ref_lrContainerId]           BIGINT        CONSTRAINT [DF_lrContainer_ref_lrContainerId] DEFAULT ((0)) NOT NULL,
    [containerLoadedCompleteDate] SMALLDATETIME NULL,
    [containerYardCutOffTime]     SMALLDATETIME NULL,
    [containerLoadedOnVessel]     SMALLDATETIME NULL,
    [customClearance]             SMALLDATETIME NULL,
    CONSTRAINT [PK_lrContainer] PRIMARY KEY CLUSTERED ([lrContainerId] ASC)
);


GO

