CREATE TABLE [dbo].[shipmentHeader] (
    [shipmentId]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [companyId]              INT             NOT NULL,
    [customerId]             INT             NOT NULL,
    [shipId]                 VARCHAR (30)    NOT NULL,
    [shipmentdate]           DATETIME        NOT NULL,
    [shipmentStatus]         INT             CONSTRAINT [DF_shipmentHeader_shipmentStatus] DEFAULT ((2149)) NOT NULL,
    [lrHeaderId]             BIGINT          NULL,
    [lrName]                 VARCHAR (50)    NULL,
    [bol]                    VARCHAR (50)    NULL,
    [invoiceId]              VARCHAR (50)    NULL,
    [invoiceDate]            DATETIME        NULL,
    [customerInvoiceNo]      VARCHAR (50)    NULL,
    [soHeaderId]             BIGINT          NOT NULL,
    [soName]                 VARCHAR (50)    NULL,
    [customerPO]             VARCHAR (50)    CONSTRAINT [DF_shipmentHeader_soReferenceId] DEFAULT ('') NOT NULL,
    [pickupAddrId]           INT             NULL,
    [shipToId]               INT             NOT NULL,
    [pol]                    VARCHAR (100)   CONSTRAINT [DF_shipmentHeader_PortOfLanding] DEFAULT ('') NULL,
    [pod]                    VARCHAR (100)   CONSTRAINT [DF_shipmentHeader_ShipmentTo] DEFAULT ('') NULL,
    [paymentTermId]          INT             NULL,
    [paymentDueDate]         DATE            NULL,
    [paymentBalance]         DECIMAL (18, 4) CONSTRAINT [DF_shipmentHeader_pymtBal] DEFAULT ((0)) NOT NULL,
    [InvoiceAmount]          DECIMAL (18, 4) CONSTRAINT [DF_shipmentHeader_shpInvAmnt] DEFAULT ((0)) NOT NULL,
    [containerTypeId]        INT             CONSTRAINT [DF_shipmentHeader_containerType] DEFAULT ((0)) NOT NULL,
    [containerSeqNo]         INT             NULL,
    [containerNo]            VARCHAR (100)   NULL,
    [containerSealNo]        VARCHAR (100)   NULL,
    [containerMaxGross]      DECIMAL (18, 4) NULL,
    [containerTare]          DECIMAL (18, 4) NULL,
    [forwarderId]            INT             NULL,
    [forwarderBookingNo]     VARCHAR (50)    NULL,
    [haulierId]              INT             NULL,
    [vesselId]               INT             CONSTRAINT [DF_shipmentHeader_Vessel] DEFAULT ('') NULL,
    [countryOfOrigin]        VARCHAR (100)   NULL,
    [ETD]                    DATE            CONSTRAINT [DF_shipmentHeader_ETD] DEFAULT ('') NULL,
    [ETA]                    DATE            CONSTRAINT [DF_shipmentHeader_ETA] DEFAULT ('') NULL,
    [containerPullIndate]    DATETIME        NULL,
    [containerPullOutDate]   DATETIME        NULL,
    [numberOfPallets]        INT             CONSTRAINT [DF_shipmentHeader_numberOfPallets] DEFAULT ((0)) NOT NULL,
    [bolTotalPallets]        INT             CONSTRAINT [DF_shipmentHeader_bolTotalPallets] DEFAULT ((0)) NOT NULL,
    [shipmentWeight]         DECIMAL (18, 4) CONSTRAINT [DF_shipmentHeader_shipmentWeight] DEFAULT ((0)) NOT NULL,
    [bolTotalShipmentWeight] DECIMAL (18, 4) CONSTRAINT [DF_shipmentHeader_bolTotalShipmentWeight] DEFAULT ((0)) NOT NULL,
    [summary]                VARCHAR (500)   CONSTRAINT [DEFAULT_shipmentHeader_summary] DEFAULT ('') NULL,
    [note]                   VARCHAR (5000)  CONSTRAINT [DF_shipmentHeader_note] DEFAULT ('') NULL,
    [apiStatus]              VARCHAR (10)    CONSTRAINT [DF_shipmentHeader_apiStatus] DEFAULT ('_NEW_') NULL,
    [apiAsn]                 VARCHAR (100)   CONSTRAINT [DF_shipmentHeader_apiASN] DEFAULT ('') NULL,
    [asnDate]                DATETIME        NULL,
    [apiInv]                 VARCHAR (100)   CONSTRAINT [DF_shipmentHeader_apiINV] DEFAULT ('') NULL,
    [invDate]                DATETIME        NULL,
    [createBy]               INT             NOT NULL,
    [createDate]             DATETIME        CONSTRAINT [DF_shipmentHeader_createDate] DEFAULT (getdate()) NOT NULL,
    [updateBy]               INT             NULL,
    [updateDate]             DATETIME        CONSTRAINT [DF_shipmentHeader_modifiedon] DEFAULT (((1900)-(1))-(1)) NULL,
    CONSTRAINT [PK_shipmentHeader_1] PRIMARY KEY CLUSTERED ([shipmentId] ASC),
    CONSTRAINT [FK_shipmentHeader_md_Customer] FOREIGN KEY ([customerId]) REFERENCES [dbo].[md_Customer] ([customerId]),
    CONSTRAINT [FK_shipmentHeader_md_ShipToDestination] FOREIGN KEY ([shipToId]) REFERENCES [dbo].[md_ShipToDestination] ([shipToId])
);


GO

