CREATE TABLE [dbo].[soHeader] (
    [soheaderId]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [companyId]         INT            NOT NULL,
    [customerId]        INT            NOT NULL,
    [supplierId]        INT            CONSTRAINT [DF_soHeader_supplierId] DEFAULT ((0)) NOT NULL,
    [soName]            VARCHAR (50)   CONSTRAINT [DF_soHeader_soName] DEFAULT ('') NOT NULL,
    [soDate]            DATE           CONSTRAINT [DF_soHeader_soDate] DEFAULT (getdate()) NOT NULL,
    [customerPO]        VARCHAR (200)  CONSTRAINT [DF_soHeader_customerPO] DEFAULT ('') NULL,
    [thirdParty]        VARCHAR (200)  NULL,
    [thirdPartyPO]      VARCHAR (500)  CONSTRAINT [DF_soHeader_thirdPartyPO] DEFAULT ('') NULL,
    [shipToId]          INT            NOT NULL,
    [shipWay]           INT            CONSTRAINT [DF_soHeader_shipWay] DEFAULT ('') NOT NULL,
    [vesselBooking]     VARCHAR (50)   CONSTRAINT [DF_soHeader_vesselBooking] DEFAULT ('') NOT NULL,
    [portOfLanding]     VARCHAR (50)   CONSTRAINT [DF_soHeader_portOfLanding] DEFAULT ('') NOT NULL,
    [portOfDestination] VARCHAR (50)   NOT NULL,
    [earlyShipDate]     DATE           NULL,
    [lateShipDate]      DATE           NULL,
    [soInvAmnt]         FLOAT (53)     CONSTRAINT [DF_soHeader_soInvAmnt] DEFAULT ((0)) NOT NULL,
    [soInvoice]         VARCHAR (200)  CONSTRAINT [DF_soHeader_soInvoice] DEFAULT ('') NOT NULL,
    [soInvoiceDate]     DATE           NULL,
    [reference1]        VARCHAR (500)  CONSTRAINT [DF_soHeader_reference1] DEFAULT ('') NULL,
    [reference2]        VARCHAR (500)  CONSTRAINT [DF_soHeader_reference2] DEFAULT ('') NULL,
    [reference3]        VARCHAR (500)  NULL,
    [soNote]            VARCHAR (1000) CONSTRAINT [DF_soHeader_soNote] DEFAULT ('') NOT NULL,
    [soStatus]          INT            NOT NULL,
    [createBy]          INT            CONSTRAINT [DF_soHeader_createBy] DEFAULT ('') NOT NULL,
    [createDate]        DATETIME       CONSTRAINT [DF_soHeader_createDate] DEFAULT (getdate()) NOT NULL,
    [updateBy]          INT            CONSTRAINT [DF_soHeader_updateBy] DEFAULT ('') NOT NULL,
    [updateDate]        DATETIME       CONSTRAINT [DF_soHeader_updateDate] DEFAULT (getdate()) NOT NULL,
    [apiStatus]         VARCHAR (10)   NULL,
    [poaDate]           DATETIME       NULL,
    [syncDate]          DATETIME       NULL,
    [ValidFrom]         DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [ValidTo]           DATETIME2 (7)  DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999')) NOT NULL,
    [lastUpdatedDate]   DATETIME       NULL,
    [locNo]             VARCHAR (20)   NULL,
    [approveBy]         INT            NULL,
    [approveDate]       DATETIME       NULL,
    CONSTRAINT [PK__soHeader__3AAE69A709337DFC] PRIMARY KEY CLUSTERED ([soheaderId] ASC),
    CONSTRAINT [FK_soHeader_md_ShipToDestination] FOREIGN KEY ([shipToId]) REFERENCES [dbo].[md_ShipToDestination] ([shipToId])
);


GO

