CREATE TABLE [dbo].[temp_inventoryLog] (
    [logId]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [productCategory]    NVARCHAR (255)  NULL,
    [productSubCategory] NVARCHAR (255)  NULL,
    [productType]        NVARCHAR (255)  NULL,
    [itemCode]           NVARCHAR (50)   NULL,
    [modelNo]            NVARCHAR (50)   NULL,
    [inventorySKU]       NVARCHAR (50)   NULL,
    [productName]        NVARCHAR (255)  NULL,
    [productPrice]       NVARCHAR (50)   NULL,
    [description]        NVARCHAR (2000) NULL,
    [grossWeight]        NVARCHAR (50)   NULL,
    [grossLength]        NVARCHAR (50)   NULL,
    [grossWidth]         NVARCHAR (50)   NULL,
    [grossHeight]        NVARCHAR (50)   NULL,
    [netWeight]          NVARCHAR (50)   NULL,
    [netLength]          NVARCHAR (50)   NULL,
    [netWidth]           NVARCHAR (50)   NULL,
    [netHeight]          NVARCHAR (50)   NULL,
    [cbm]                NVARCHAR (50)   NULL,
    [measurement]        NVARCHAR (20)   NULL,
    [color]              NVARCHAR (255)  NULL,
    [packaging]          NVARCHAR (255)  NULL,
    [size]               NVARCHAR (255)  NULL,
    [glCode]             NVARCHAR (50)   NULL,
    [virtualProduct]     NVARCHAR (1)    NULL,
    [isBuffer]           NVARCHAR (1)    NULL,
    [attributeName_1]    NVARCHAR (100)  NULL,
    [attributeValue_1]   NVARCHAR (100)  NULL,
    [attributeName_2]    NVARCHAR (100)  NULL,
    [attributeValue_2]   NVARCHAR (100)  NULL,
    [attributeName_3]    NVARCHAR (100)  NULL,
    [attributeValue_3]   NVARCHAR (100)  NULL,
    [attributeName_4]    NVARCHAR (100)  NULL,
    [attributeValue_4]   NVARCHAR (100)  NULL,
    [attributeName_5]    NVARCHAR (100)  NULL,
    [attributeValue_5]   NVARCHAR (100)  NULL,
    [attributeName_6]    NVARCHAR (100)  NULL,
    [attributeValue_6]   NVARCHAR (100)  NULL,
    [attributeName_7]    NVARCHAR (100)  NULL,
    [attributeValue_7]   NVARCHAR (100)  NULL,
    [attributeName_8]    NVARCHAR (100)  NULL,
    [attributeValue_8]   NVARCHAR (100)  NULL,
    [attributeName_9]    NVARCHAR (100)  NULL,
    [attributeValue_9]   NVARCHAR (100)  NULL,
    [attributeName_10]   NVARCHAR (100)  NULL,
    [attributeValue_10]  NVARCHAR (100)  NULL,
    [fileName]           VARCHAR (150)   NULL,
    CONSTRAINT [PK_FileDump_Inventory_logId] PRIMARY KEY CLUSTERED ([logId] ASC)
);


GO

